// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORMdoga.Models;

#nullable disable

namespace ORMdoga.Migrations
{
    [DbContext(typeof(ZeneDBContext))]
    [Migration("20240104081709_ThirdMigration")]
    partial class ThirdMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ORMdoga.Models.Eloado", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EloadoNemzetiseg")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EloadoNev")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ZeneFajta")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Eloado");
                });

            modelBuilder.Entity("ORMdoga.Models.Szam", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EloadoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SzamCim")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SzamMegjelenes")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.HasIndex("EloadoId");

                    b.ToTable("Szam");
                });

            modelBuilder.Entity("ORMdoga.Models.Szam", b =>
                {
                    b.HasOne("ORMdoga.Models.Eloado", "Eloado")
                        .WithMany()
                        .HasForeignKey("EloadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eloado");
                });
#pragma warning restore 612, 618
        }
    }
}
